// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/greetings/greetings.proto

package greetings

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa72f2f078a14ba4, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GreetReq struct {
	Request              *Greeting `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetReq) Reset()         { *m = GreetReq{} }
func (m *GreetReq) String() string { return proto.CompactTextString(m) }
func (*GreetReq) ProtoMessage()    {}
func (*GreetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa72f2f078a14ba4, []int{1}
}

func (m *GreetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetReq.Unmarshal(m, b)
}
func (m *GreetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetReq.Marshal(b, m, deterministic)
}
func (m *GreetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetReq.Merge(m, src)
}
func (m *GreetReq) XXX_Size() int {
	return xxx_messageInfo_GreetReq.Size(m)
}
func (m *GreetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetReq proto.InternalMessageInfo

func (m *GreetReq) GetRequest() *Greeting {
	if m != nil {
		return m.Request
	}
	return nil
}

type GreetResp struct {
	Response             *Greeting `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetResp) Reset()         { *m = GreetResp{} }
func (m *GreetResp) String() string { return proto.CompactTextString(m) }
func (*GreetResp) ProtoMessage()    {}
func (*GreetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa72f2f078a14ba4, []int{2}
}

func (m *GreetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResp.Unmarshal(m, b)
}
func (m *GreetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResp.Marshal(b, m, deterministic)
}
func (m *GreetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResp.Merge(m, src)
}
func (m *GreetResp) XXX_Size() int {
	return xxx_messageInfo_GreetResp.Size(m)
}
func (m *GreetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResp proto.InternalMessageInfo

func (m *GreetResp) GetResponse() *Greeting {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greetings.Greeting")
	proto.RegisterType((*GreetReq)(nil), "greetings.GreetReq")
	proto.RegisterType((*GreetResp)(nil), "greetings.GreetResp")
}

func init() { proto.RegisterFile("services/greetings/greetings.proto", fileDescriptor_fa72f2f078a14ba4) }

var fileDescriptor_fa72f2f078a14ba4 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x4f, 0x2f, 0x4a, 0x4d, 0x2d, 0xc9, 0xcc, 0x4b, 0x47, 0x62, 0xe9,
	0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x71, 0xc2, 0x05, 0x94, 0x64, 0xb8, 0x38, 0xdc, 0xa1, 0x1c,
	0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53,
	0xc9, 0x12, 0x2a, 0x1b, 0x94, 0x5a, 0x28, 0xa4, 0xcb, 0xc5, 0x5e, 0x94, 0x5a, 0x58, 0x9a, 0x5a,
	0x5c, 0x02, 0x56, 0xc1, 0x6d, 0x24, 0xac, 0x87, 0x30, 0x17, 0x66, 0x46, 0x10, 0x4c, 0x8d, 0x92,
	0x0d, 0x17, 0x27, 0x54, 0x6b, 0x71, 0x81, 0x90, 0x3e, 0x17, 0x47, 0x51, 0x6a, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0x2a, 0x3e, 0xcd, 0x70, 0x45, 0x46, 0x6e, 0x5c, 0x7c, 0x60, 0xd1, 0xd4, 0xa2, 0x60,
	0x88, 0x77, 0x84, 0x4c, 0xb8, 0x58, 0xc1, 0x22, 0x42, 0x18, 0x3a, 0x83, 0x52, 0x0b, 0xa5, 0x44,
	0x30, 0x05, 0x8b, 0x0b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x1e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x67, 0xa0, 0x23, 0x6a, 0x16, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterServiceClient interface {
	Greet(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResp, error)
}

type greeterServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreeterServiceClient(cc *grpc.ClientConn) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) Greet(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResp, error) {
	out := new(GreetResp)
	err := c.cc.Invoke(ctx, "/greetings.GreeterService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServiceServer is the server API for GreeterService service.
type GreeterServiceServer interface {
	Greet(context.Context, *GreetReq) (*GreetResp, error)
}

func RegisterGreeterServiceServer(s *grpc.Server, srv GreeterServiceServer) {
	s.RegisterService(&_GreeterService_serviceDesc, srv)
}

func _GreeterService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetings.GreeterService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Greet(ctx, req.(*GreetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetings.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreeterService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/greetings/greetings.proto",
}
